### ISSUE TITLE
manage_agents unable to access /dev/random due to chroot

### ISSUE THREAD

**Issue by netflash** [wazuh/ossec-wazuh#11]
Hi.

I was trying to implement this https://github.com/wazuh/docker-ossec/blob/master/Dockerfile#L14
to this fork.

And I'm struggling from the same issue https://github.com/ossec/ossec-hids/issues/425
Get same error just in Ubuntu 14.04.3 and also inside of your docker ELK container.

```
root@642f170bea07:/# echo "127.0.0.1,DEFAULT_LOCAL_AGENT" > /var/ossec/default_agent
root@642f170bea07:/# /var/ossec/bin/manage_agents -f /default_agent
Bulk load file: /default_agent
Opening: [/default_agent]
2016/01/20 16:00:21 manage_agents: ERROR: randombytes failed for all possible methods for accessing random data
root@642f170bea07:/# strace /var/ossec/bin/manage_agents -f /default_agent
bash: strace: command not found
root@642f170bea07:/# apt-get install strace
Reading package lists... Done
...
Setting up strace (4.8-1ubuntu5) ...

root@642f170bea07:/# strace /var/ossec/bin/manage_agents -f /default_agent
execve("/var/ossec/bin/manage_agents", ["/var/ossec/bin/manage_agents", "-f", "/default_agent"], [/* 9 vars */]) = 0
brk(0)                                  = 0x16fd000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbbbacfc000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=16378, ...}) = 0
mmap(NULL, 16378, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbbbacf8000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0po\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=141574, ...}) = 0
mmap(NULL, 2217264, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbbba8be000
mprotect(0x7fbbba8d7000, 2093056, PROT_NONE) = 0
mmap(0x7fbbbaad6000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18000) = 0x7fbbbaad6000
mmap(0x7fbbbaad8000, 13616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbbbaad8000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\37\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1840928, ...}) = 0
mmap(NULL, 3949248, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbbba4f9000
mprotect(0x7fbbba6b4000, 2093056, PROT_NONE) = 0
mmap(0x7fbbba8b3000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7fbbba8b3000
mmap(0x7fbbba8b9000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbbba8b9000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbbbacf7000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbbbacf5000
arch_prctl(ARCH_SET_FS, 0x7fbbbacf5740) = 0
mprotect(0x7fbbba8b3000, 16384, PROT_READ) = 0
mprotect(0x7fbbbaad6000, 4096, PROT_READ) = 0
mprotect(0x625000, 4096, PROT_READ)     = 0
mprotect(0x7fbbbacfe000, 4096, PROT_READ) = 0
munmap(0x7fbbbacf8000, 16378)           = 0
set_tid_address(0x7fbbbacf5a10)         = 435
set_robust_list(0x7fbbbacf5a20, 24)     = 0
futex(0x7fff6edf4ef0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 7fbbbacf5740) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGRTMIN, {0x7fbbba8c49f0, [], SA_RESTORER|SA_SIGINFO, 0x7fbbba8ce340}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7fbbba8c4a80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fbbba8ce340}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 9), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbbbacfb000
write(1, "Bulk load file: /default_agent\n", 31Bulk load file: /default_agent
) = 31
open("/dev/urandom", O_RDONLY)          = 3
read(3, ")\262\375\354", 4)             = 4
close(3)                                = 0
brk(0)                                  = 0x16fd000
brk(0x171e000)                          = 0x171e000
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=475, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbbbacfa000
read(3, "# /etc/nsswitch.conf\n#\n# Example"..., 4096) = 475
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7fbbbacfa000, 4096)            = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=16378, ...}) = 0
mmap(NULL, 16378, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbbbacf1000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libnss_compat.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\23\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=39824, ...}) = 0
mmap(NULL, 2135368, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbbba2ef000
mprotect(0x7fbbba2f8000, 2093056, PROT_NONE) = 0
mmap(0x7fbbba4f7000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8000) = 0x7fbbba4f7000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libnsl.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`A\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=97296, ...}) = 0
mmap(NULL, 2202328, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbbba0d5000
mprotect(0x7fbbba0ec000, 2093056, PROT_NONE) = 0
mmap(0x7fbbba2eb000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16000) = 0x7fbbba2eb000
mmap(0x7fbbba2ed000, 6872, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbbba2ed000
close(3)                                = 0
mprotect(0x7fbbba2eb000, 4096, PROT_READ) = 0
mprotect(0x7fbbba4f7000, 4096, PROT_READ) = 0
munmap(0x7fbbbacf1000, 16378)           = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=16378, ...}) = 0
mmap(NULL, 16378, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbbbacf1000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libnss_nis.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240!\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=47760, ...}) = 0
mmap(NULL, 2143784, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbbb9ec9000
mprotect(0x7fbbb9ed4000, 2093056, PROT_NONE) = 0
mmap(0x7fbbba0d3000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa000) = 0x7fbbba0d3000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240\"\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=47712, ...}) = 0
mmap(NULL, 2144392, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbbb9cbd000
mprotect(0x7fbbb9cc8000, 2093056, PROT_NONE) = 0
mmap(0x7fbbb9ec7000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa000) = 0x7fbbb9ec7000
close(3)                                = 0
mprotect(0x7fbbb9ec7000, 4096, PROT_READ) = 0
mprotect(0x7fbbba0d3000, 4096, PROT_READ) = 0
munmap(0x7fbbbacf1000, 16378)           = 0
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
lseek(3, 0, SEEK_CUR)                   = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=599, ...}) = 0
mmap(NULL, 599, PROT_READ, MAP_SHARED, 3, 0) = 0x7fbbbacfa000
lseek(3, 599, SEEK_SET)                 = 599
munmap(0x7fbbbacfa000, 599)             = 0
close(3)                                = 0
setgroups(1, [8378])                    = 0
setresgid(-1, 8378, -1)                 = 0
setgid(8378)                            = 0
chdir(0x41a56b)                         = 0
chroot(0x41a56b)                        = 0
chdir(0x41ca4d)                         = 0
rt_sigaction(SIGHUP, {...}, {...}, 8)   = 0
rt_sigaction(SIGINT, {...}, {...}, 8)   = 0
rt_sigaction(SIGQUIT, {...}, {...}, 8)  = 0
rt_sigaction(SIGTERM, {...}, {...}, 8)  = 0
rt_sigaction(SIGALRM, {...}, {...}, 8)  = 0
rt_sigaction(SIGPIPE, {...}, {...}, 8)  = 0
write(1, 0x7fbbbacfb000, 26Opening: [/default_agent]
)            = 26
open(0x7fff6edf6efc, O_RDONLY)          = 3
open(0x41b349, O_WRONLY|O_CREAT|O_APPEND, 0666) = 4
fstat(4, {...})                         = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbbbacfa000
fstat(4, {...})                         = 0
lseek(4, 0, SEEK_SET)                   = 0
close(4)                                = 0
munmap(0x7fbbbacfa000, 4096)            = 0
fstat(3, {...})                         = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbbbacfa000
read(3, 0x7fbbbacfa000, 4096)           = 30
chmod(0x41b349, 0440)                   = 0
open(0x41cd72, O_RDONLY)                = -1 ENOENT (No such file or directory)
open(0x41cd7f, O_RDONLY)                = -1 ENOENT (No such file or directory)
open(0x7fbbba6771f0, O_RDONLY|O_CLOEXEC) = 4
fstat(4, {...})                         = 0
fstat(4, {...})                         = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbbbacf9000
read(4, 0x7fbbbacf9000, 4096)           = 118
lseek(4, -62, SEEK_CUR)                 = 56
read(4, 0x7fbbbacf9000, 4096)           = 62
close(4)                                = 0
munmap(0x7fbbbacf9000, 4096)            = 0
open(0x41c9e8, O_WRONLY|O_CREAT|O_APPEND, 0666) = 4
fstat(4, {...})                         = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbbbacf9000
fstat(4, {...})                         = 0
lseek(4, 24258, SEEK_SET)               = 24258
write(4, 0x7fbbbacf9000, 112)           = 112
close(4)                                = 0
munmap(0x7fbbbacf9000, 4096)            = 0
write(2, 0x7fff6edf1fb0, 202016/01/20 16:01:01 )            = 20
write(2, 0x7fff6edf2080, 91manage_agents: ERROR: randombytes failed for all possible methods for accessing random data)            = 91
write(2, 0x7fbbba8b8243, 1
)             = 1
exit_group(1)                           = ?
+++ exited with 1 +++
```

this mentioned workaround https://github.com/ossec/ossec-hids/issues/425#issuecomment-61238405 also fixes the issue

```
cd /var/ossec/
mkdir dev
mount -o bind /dev dev/
```

I have checked the code and this fix https://github.com/ossec/ossec-hids/issues/426 exists in custom repo.

Could you please have a look into this issue ?

**Comment by snaow** [comment]
Hi @netflash,

We are already reviewing this issue, it is important to fix this error because we are currently using this bulk option in our API.

Mount dev folder inside ossec folder is a solution but it is not elegant or secure.


In few days I will update this post with the status of this issue.

Thanks for your feedback, 

Pedro.

**Comment by snaow** [comment]
Solved in https://github.com/wazuh/ossec-wazuh/commit/2a501598048390b34afe919d447a4980c0d26d9f and added into release 1.0.2

Thanks for your feedback,

Pedro.

**Comment by stideswell** [comment]
Hmmph. If you enable writing to the DB (Postgresql) and you are using this source https://github.com/wazuh/wazuh/archive/v2.1.0.tar.gz then the issue persists ...
_"2017/11/15 17:48:59 ossec-dbd: CRITICAL: randombytes failed for all possible methods for accessing random data"_
So **wazuh-server** starts, but **os_dbd** fails to start. The mount-bind trick resolves the issue, but it is quite inelegant. I'm running Ubuntu 16.04.

**Comment by vikman90** [comment]
Hi @stideswell,

I have just fixed this problem: https://github.com/wazuh/wazuh/commit/ff64c5c3a5ba5f518f7040036ac809fb8fc3fc7d

Anyway, this doesn't fix issue https://github.com/wazuh/wazuh/issues/261. @crolopez is investigating it and will respond as soon as possible.

Thanks for reporting!
Best regards.
